import fixture from "../docs/fixtures/expansion-1-r4-chapter-1-human-evidence.json";
import { createExpansionScoreApi, expansionScoreApi, type ExpansionSubmitResult } from "../src/leaderboard/expansionScoreApi";
import { ExpansionPendingScores } from "../src/leaderboard/expansionPendingScore";
import type { ExpansionReplayInput } from "../src/sim/expansion/types";
import { expansionScoreCategory } from "../src/leaderboard/expansionScoreProtocol";
import assert from "./assert";
const proof = fixture.runs[0]!.replay as ExpansionReplayInput;
const nextProof = { ...proof, seed: "another-run" };
const success: ExpansionSubmitResult = { ok: true, improved: true, runScore: 100, bestScore: 100, levelRank: 1, rating: "A", handle: "Tester", category: expansionScoreCategory(proof.level), level: proof.level, contentRevision: proof.contentRevision };
const config = { enabled: true, url: "https://isolated.invalid", anonKey: "test-public", gameSlug: "gridwatch-signal-breach" };
const REGISTRY = [{ id: "00000000-0000-4000-8000-0000000000e4", game_slug: "gridwatch-signal-breach", key: "expansion", ruleset: "r4", status: "active" }];
let requests = 0;
let response: unknown = success;
const fakeFetch: typeof fetch = async (url, init) => {
  requests++;
  assert.equal(new URL(String(url)).origin, config.url);
  assert.equal(init?.method, "POST");
  const body = JSON.parse(String(init?.body));
  if (String(url).includes("/functions/")) {
    assert.equal(new Headers(init?.headers).get("Authorization"), "Bearer isolated-token");
    assert.deepEqual(body, proof);
    assert.equal("score" in body, false);
  } else if (String(url).endsWith("/rest/v1/rpc/list_boards")) {
    assert.deepEqual(body, { p_game_slug: config.gameSlug });
    return Response.json(REGISTRY);
  } else {
    assert.equal(String(url), `${config.url}/rest/v1/rpc/get_board_entry`);
    assert.deepEqual(body, { p_board_id: REGISTRY[0]!.id, p_period_key: "all", p_entry_key: `level:${proof.level}`, p_limit: 20 });
  }
  return Response.json(response);
};
const api = createExpansionScoreApi(config, fakeFetch);
assert.equal((await api.submit(proof, "isolated-token")).ok, true);
response = { ...success, category: "phase4-v1:global" };
assert.equal((await api.submit(proof, "isolated-token")).ok, false);
response = null;
assert.equal((await api.submit(proof, "isolated-token")).ok, false);
response = [{ rank: 1, display_name: "<not-html>", score: 100, achieved_at: "2026-09-25T12:00:00Z", is_you: false }];
const read = await api.read(proof.level);
assert.equal(read.ok && read.entries[0]!.handle, "<not-html>", "display_name maps onto the row handle.");
response = [{ rank: 0, display_name: "x", score: 100 }];
assert.equal((await api.read(proof.level)).ok, false);
const offline = createExpansionScoreApi(config, async () => { throw Error("offline"); });
assert.equal((await offline.submit(proof, "x")).ok, false);
assert.equal((await offline.read(1)).ok, false);
const disabled = createExpansionScoreApi({ ...config, enabled: false }, fakeFetch);
const before = requests;
assert.equal((await disabled.submit(proof, "x")).ok, false);
assert.equal((await disabled.read(1)).ok, false);
assert.equal(requests, before);
assert.equal(expansionScoreApi.enabled, true, "Scores are enabled after the compatible server release.");
let bodyAborted = false;
const stalledBody = createExpansionScoreApi(config, async (_url, init) => new Response(new ReadableStream({
  start(controller) {
    init?.signal?.addEventListener("abort", () => { bodyAborted = true; controller.error(new Error("timeout")); }, { once: true });
  },
})));
assert.equal((await stalledBody.read(proof.level)).ok, false);
assert.equal(bodyAborted, true, "The 10-second deadline must include response JSON, not only headers.");

const map = new Map<string, string>();
const storage = { getItem: (k: string) => map.get(k) ?? null, setItem: (k: string, v: string) => { map.set(k, v); }, removeItem: (k: string) => { map.delete(k); } };
let owner: string | undefined = "alice";
let sent = 0;
let session = async () => ({ user: { id: "alice" }, access_token: "isolated-token" });
let submit = async (): Promise<ExpansionSubmitResult> => { sent++; return success; };
const pending = new ExpansionPendingScores(storage, { owner: () => owner, session: () => session(), submit: () => submit() });
assert.equal(pending.stage(proof, "guest"), true);
assert.equal(pending.read("alice"), null);
submit = async () => { sent++; return { ok: false, error: "offline" }; };
assert.equal((await pending.submit(pending.read("guest")!)).ok, false);
assert.equal(pending.read("guest"), null, "Claim is durable before request; cannot switch guest score to another account after failure.");
assert.deepEqual(pending.read("alice")?.proof, proof);
owner = "bob";
const count = sent;
assert.equal((await pending.submit(pending.read("alice")!)).ok, false);
assert.equal(sent, count);
owner = "alice";
session = async () => { owner = "bob"; pending.invalidate(); return { user: { id: "alice" }, access_token: "x" }; };
assert.equal((await pending.submit(pending.read("alice")!)).ok, false);
assert.equal(sent, count, "Account switch during token lookup sends nothing.");
owner = "alice";
session = async () => ({ user: { id: "alice" }, access_token: "x" });
submit = async () => { sent++; owner = "bob"; pending.invalidate(); return success; };
assert.equal((await pending.submit(pending.read("alice")!)).ok, false);
assert.deepEqual(pending.read("alice")?.proof, proof, "Stale completion cannot clear previous account state.");
owner = "alice";
submit = async () => { sent++; pending.stage(nextProof, "alice"); return success; };
assert.equal((await pending.submit(pending.read("alice")!)).ok, true);
assert.deepEqual(pending.read("alice")?.proof, nextProof, "Newer run survives older request completion.");
const stale = { owner: "alice", proof };
assert.equal((await pending.submit(stale)).ok, false);
submit = async () => { sent++; return success; };
assert.equal((await pending.submit(pending.read("alice")!)).ok, true);
assert.equal(pending.read("alice"), null);
pending.stage(proof, "guest"); pending.stage(nextProof, "alice");
assert.equal((await pending.submit(pending.read("guest")!)).ok, false, "Guest claim never silently replaces an account run.");
let resolve!: (result: ExpansionSubmitResult) => void;
submit = () => new Promise((done) => { resolve = done; });
const flight = pending.submit(pending.read("alice")!);
await Promise.resolve();
assert.equal((await pending.submit(pending.read("alice")!)).ok, false, "Double-click sends only one request.");
resolve(success); await flight;
const unavailable = new ExpansionPendingScores(null, { owner: () => owner, session, submit });
assert.equal(unavailable.stage(proof, "alice"), false);
assert.equal(unavailable.read("alice"), null);
console.log("Expansion score client: release latch, exact transport/category, invalid/offline responses, durable guest claim, owner/token races, stale writes, double-submit and storage failure passed.");
