// Server-side score validator for "GridWatch: Signal Breach".
//
// Anti-cheat: the game simulation is pure and deterministic, so this function
// REPLAYS the submitted run with the exact game code (bundled into
// ./sim.bundle.js from src/sim) and stores the score IT computes. The number a
// client claims is never trusted. A tampered or unfinished run is rejected.
//
// sim.bundle.js is generated by `npm run build:validator`; do not edit it by
// hand. A CI drift-guard keeps it identical to src/sim.
import { createClient } from "jsr:@supabase/supabase-js@2";
// The validator bundle (generated from src/sim by `npm run build:validator`) is
// imported from a pinned, immutable commit on the public repo. Supabase resolves
// and bakes this in at deploy time, so the function stays self-contained. After
// any src/sim change: regenerate the bundle, commit, repin this SHA, redeploy.
// Local/CLI use can instead import "./sim.bundle.js" (the committed copy).
import {
  replayRun,
  ReplayError,
} from "https://raw.githubusercontent.com/remeadows/gridwatch-signal-breach/fa0a5df7a5bae70068772566913d13e99fe137f0/supabase/functions/submit-gridwatch-score/sim.bundle.js";

const GAME_SLUG = "gridwatch-signal-breach";
const MAX_COMMANDS = 5000;
const MAX_HANDLE_LENGTH = 12;
const MAX_SCORE = 100000;
const ALLOWED_COMMAND_TYPES = new Set(["placeUnit", "sellUnit", "skipPrep"]);
const VALID_SECTORS = new Set([1, 2, 3]);

const ALLOWED_ORIGINS = new Set([
  "https://GridWatch-SignalBreach.warsignallabs.net",
  "https://gridwatch-signalbreach.warsignallabs.net",
  "http://localhost:5173",
  "http://127.0.0.1:5173",
]);

function corsHeaders(origin: string | null): Record<string, string> {
  const allowed = origin && ALLOWED_ORIGINS.has(origin) ? origin : "null";
  return {
    "Access-Control-Allow-Origin": allowed,
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "authorization, apikey, content-type",
    Vary: "Origin",
  };
}

function json(body: unknown, status: number, origin: string | null): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json", ...corsHeaders(origin) },
  });
}

function sanitizeHandle(raw: unknown): string {
  if (typeof raw !== "string") {
    return "ANON";
  }
  // Drop control characters, collapse whitespace, cap length.
  const cleaned = raw
    .replace(/[\u0000-\u001F\u007F]/g, "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, MAX_HANDLE_LENGTH);
  const scrubbed = cleaned.replace(
    /\b(fuck|shit|cunt|nigger|faggot)\b/gi,
    "****",
  );
  return scrubbed.length > 0 ? scrubbed : "ANON";
}

function isValidCommandEnvelope(entry: unknown): boolean {
  if (typeof entry !== "object" || entry === null) {
    return false;
  }
  const { t, c } = entry as { t: unknown; c: unknown };
  if (typeof t !== "number" || !Number.isInteger(t) || t < 0) {
    return false;
  }
  if (typeof c !== "object" || c === null) {
    return false;
  }
  const type = (c as { type: unknown }).type;
  return typeof type === "string" && ALLOWED_COMMAND_TYPES.has(type);
}

function canonicalizePosition(raw: unknown): { x: number; y: number } | null {
  if (typeof raw !== "object" || raw === null) {
    return null;
  }
  const { x, y } = raw as { x: unknown; y: unknown };
  if (
    typeof x !== "number" ||
    !Number.isInteger(x) ||
    typeof y !== "number" ||
    !Number.isInteger(y)
  ) {
    return null;
  }
  return { x, y };
}

// Rebuilds the command log from only the fields the simulation actually reads,
// in a fixed key order. Inert extra fields a client might pad in can't then
// alter the proof hash, so the same logical run always hashes identically and
// duplicate detection can't be bypassed by spamming variants. Throws on a
// malformed command (mirrors the replay engine's own rejection).
function canonicalizeCommands(
  commands: readonly unknown[],
): Array<{ t: number; c: Record<string, unknown> }> {
  const out: Array<{ t: number; c: Record<string, unknown> }> = [];
  for (const entry of commands) {
    const { t, c } = entry as { t: number; c: { type: string } & Record<string, unknown> };
    switch (c.type) {
      case "skipPrep":
        out.push({ t, c: { type: "skipPrep" } });
        break;
      case "sellUnit": {
        const position = canonicalizePosition(c.position);
        if (!position) {
          throw new ReplayError("Malformed command log.");
        }
        out.push({ t, c: { type: "sellUnit", position } });
        break;
      }
      case "placeUnit": {
        const position = canonicalizePosition(c.position);
        if (!position || typeof c.unit !== "string") {
          throw new ReplayError("Malformed command log.");
        }
        out.push({ t, c: { type: "placeUnit", position, unit: c.unit } });
        break;
      }
      default:
        throw new ReplayError("Malformed command log.");
    }
  }
  return out;
}

async function sha256Hex(input: string): Promise<string> {
  const data = new TextEncoder().encode(input);
  const digest = await crypto.subtle.digest("SHA-256", data);
  return Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

Deno.serve(async (req: Request) => {
  const origin = req.headers.get("origin");

  if (req.method === "OPTIONS") {
    return new Response(null, { status: 204, headers: corsHeaders(origin) });
  }
  if (req.method !== "POST") {
    return json({ ok: false, error: "Method not allowed." }, 405, origin);
  }

  let payload: {
    seed?: unknown;
    sector?: unknown;
    commands?: unknown;
    handle?: unknown;
  };
  try {
    payload = await req.json();
  } catch {
    return json({ ok: false, error: "Invalid JSON body." }, 400, origin);
  }

  const seed = payload.seed;
  const sector = payload.sector;
  const commands = payload.commands;

  if (typeof seed !== "string" || seed.length === 0 || seed.length > 200) {
    return json({ ok: false, error: "Invalid seed." }, 400, origin);
  }
  if (typeof sector !== "number" || !VALID_SECTORS.has(sector)) {
    return json({ ok: false, error: "Invalid sector." }, 400, origin);
  }
  if (!Array.isArray(commands) || commands.length > MAX_COMMANDS) {
    return json(
      { ok: false, error: "Invalid or oversized command log." },
      400,
      origin,
    );
  }

  // Validate command shapes + non-decreasing ticks before replay.
  let previousTick = 0;
  for (const entry of commands) {
    if (!isValidCommandEnvelope(entry)) {
      return json({ ok: false, error: "Malformed command log." }, 400, origin);
    }
    const t = (entry as { t: number }).t;
    if (t < previousTick) {
      return json(
        { ok: false, error: "Command log is out of order." },
        400,
        origin,
      );
    }
    previousTick = t;
  }

  const handle = sanitizeHandle(payload.handle);

  // Replay with the real game logic — this is the authoritative score.
  let score: number;
  let rating: string;
  let phase: string;
  let metadata: Record<string, unknown>;
  let canonicalCommands: Array<{ t: number; c: Record<string, unknown> }>;
  try {
    canonicalCommands = canonicalizeCommands(commands);
    const result = replayRun({ seed, sector, commands: canonicalCommands });
    const breakdown = result.score;
    const state = result.state;
    score = breakdown.total;
    rating = breakdown.rating;
    phase = state.phase;
    metadata = {
      sector,
      phase,
      integrity: breakdown.integrity,
      neutralized: breakdown.neutralized,
      uptimePercent: breakdown.uptimePercent,
      efficiencyBonus: breakdown.efficiencyBonus,
    };
  } catch (err) {
    if (err instanceof ReplayError) {
      return json({ ok: false, error: `Rejected: ${err.message}` }, 422, origin);
    }
    return json({ ok: false, error: "Replay failed." }, 422, origin);
  }

  if (phase !== "won" && phase !== "lost") {
    return json(
      { ok: false, error: "Run did not reach a finished state." },
      422,
      origin,
    );
  }
  if (!Number.isFinite(score) || score < 0 || score > MAX_SCORE) {
    return json({ ok: false, error: "Score out of bounds." }, 422, origin);
  }

  const category = `sector:${sector}`;
  const proof = { seed, sector, commands: canonicalCommands };
  const proofHash = await sha256Hex(JSON.stringify(proof));

  // Service-role client bypasses RLS. These env vars are injected into every
  // Supabase Edge Function automatically.
  const admin = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
    { auth: { persistSession: false } },
  );

  const { data: game, error: gameError } = await admin
    .from("games")
    .select("id")
    .eq("slug", GAME_SLUG)
    .single();

  if (gameError || !game) {
    return json({ ok: false, error: "Game not registered." }, 500, origin);
  }
  const gameId = game.id as string;

  const { error: insertError } = await admin.from("scores").insert({
    game_id: gameId,
    category,
    handle,
    score,
    rating,
    metadata,
    proof,
    proof_hash: proofHash,
  });

  let duplicate = false;
  if (insertError) {
    // 23505 = unique_violation → this exact run was already submitted.
    if (insertError.code === "23505") {
      duplicate = true;
    } else {
      return json({ ok: false, error: "Could not save score." }, 500, origin);
    }
  }

  // Ranks = (number of strictly-higher scores) + 1.
  const { count: higherGlobal, error: higherGlobalError } = await admin
    .from("scores")
    .select("id", { count: "exact", head: true })
    .eq("game_id", gameId)
    .gt("score", score);
  const { count: higherSector, error: higherSectorError } = await admin
    .from("scores")
    .select("id", { count: "exact", head: true })
    .eq("game_id", gameId)
    .eq("category", category)
    .gt("score", score);

  // Without this, a failed count silently coalesces to 0 and reports rank #1.
  if (higherGlobalError || higherSectorError) {
    return json({ ok: false, error: "Could not compute rank." }, 500, origin);
  }

  return json(
    {
      ok: true,
      duplicate,
      globalRank: (higherGlobal ?? 0) + 1,
      sectorRank: (higherSector ?? 0) + 1,
      score,
      rating,
      handle,
    },
    200,
    origin,
  );
});
